"""Public domain models for the PlaNU backend."""

from .course import Category, ClassTime, Course, Day, normalize_course_category, time_to_minutes
from .course_load import (
    CourseLoadCalculationResult,
    CourseLoadTarget,
    CourseLoadWarning,
)
from .general_course_pool import (
    ExcludedCourseDiagnostic,
    GeneralCoursePoolResult,
    GeneralCoursePools,
)
from .input_timetable import InputTimetable
from .major_selection import (
    AmbiguousMajorCourse,
    MajorCourseMatchResult,
    MajorCourseReference,
    MajorSelectionParseResult,
    MatchedMajorCourse,
    UnmatchedMajorCourse,
)
from .preference import (
    ExcludedTimeRange,
    PreferenceParseResult,
    PreferenceParseStatus,
    PreferenceRules,
    PreferenceTemplate,
    PreferenceToolStatus,
    PreferenceToolUsage,
    PreferenceTraceEvent,
    TimeRange,
    merge_preference_rules,
)
from .timetable import (
    CourseLoadSatisfaction,
    GenerationDiagnostic,
    RankingDiagnostic,
    RankingResult,
    RankingTemplate,
    ScheduleItem,
    ScoreComponent,
    ScoreDetail,
    Timetable,
    TimetableCandidate,
    TimetableGenerationCandidate,
    TimetableGenerationResult,
    TimetableRankingResult,
)

__all__ = [
    "Category",
    "ClassTime",
    "Course",
    "CourseLoadSatisfaction",
    "CourseLoadCalculationResult",
    "CourseLoadTarget",
    "CourseLoadWarning",
    "Day",
    "ExcludedTimeRange",
    "ExcludedCourseDiagnostic",
    "GeneralCoursePoolResult",
    "GeneralCoursePools",
    "GenerationDiagnostic",
    "InputTimetable",
    "AmbiguousMajorCourse",
    "MajorCourseMatchResult",
    "MajorCourseReference",
    "MajorSelectionParseResult",
    "MatchedMajorCourse",
    "PreferenceParseResult",
    "PreferenceParseStatus",
    "PreferenceRules",
    "PreferenceTemplate",
    "PreferenceToolStatus",
    "PreferenceToolUsage",
    "PreferenceTraceEvent",
    "RankingDiagnostic",
    "RankingResult",
    "RankingTemplate",
    "ScheduleItem",
    "ScoreComponent",
    "ScoreDetail",
    "TimeRange",
    "Timetable",
    "TimetableCandidate",
    "TimetableGenerationCandidate",
    "TimetableGenerationResult",
    "TimetableRankingResult",
    "UnmatchedMajorCourse",
    "merge_preference_rules",
    "normalize_course_category",
    "time_to_minutes",
]
